language: go

go:
    - "1.14.x"

script:
    - env GO111MODULE=on make

os:
    - linux
    - osx

notifications:
    email:
        recipients:
            - chadtakahashi@gmail.com
        on_success: always
        on_failure: always
